# Generated by Django 3.0.3 on 2020-04-03 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='部活名')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
            ],
        ),
    ]
