# Generated by Django 3.0.3 on 2020-04-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='club',
            field=models.ManyToManyField(to='employee.Club', verbose_name='部活'),
        ),
    ]
